# Generated by Django 2.0.7 on 2019-05-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productprice',
            old_name='price_end_date',
            new_name='offer_end_date',
        ),
        migrations.RenameField(
            model_name='productprice',
            old_name='price_start_date',
            new_name='offer_start_date',
        ),
    ]
